"""add_images_relationship2

Revision ID: 0a46dda52fc9
Revises: d4c5fb1e5e73
Create Date: 2026-04-29 21:18:08.716212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a46dda52fc9'
down_revision: Union[str, Sequence[str], None] = 'd4c5fb1e5e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
